### ISSUE TITLE
[1.12.2] Crash on Server

### ISSUE THREAD

**Issue by MokahTGS** [OreCruncher/Doodads#5]
Getting a crash with version

Crash Log: https://pastebin.com/YfqkA5Z7

OreLib-1.12.2-3.5.1.1BETA
Patchwork-1.12.2-0.2.3.0BETA

**Comment by OreCruncher** [comment]
Dedicated server?

**Comment by OreCruncher** [comment]
Pushed v0.2.3.1 to CurseForge.
