### ISSUE TITLE
[1.12.2] Game crash upon respawning near... 3D Furnaces?

### ISSUE THREAD

**Issue by SonicX8000** [OreCruncher/Doodads#6]
Minecraft: 1.12.2
Forge: 14.23.5.2795

Mods: 4
*Baubles-1.12-1.5.2*
*jei_1.12.2-4.14.3.237*
*OreLib-1.12.2-3.5.1.0BETA*
*Patchwork-1.12.2-0.2.3.1BETA*

Crash Report
https://pastebin.com/PU6DZ6Cb

-----

Sometimes when respawning after dying near the 3D Furnaces... a random crash can occur. Tried with /kill while looking there, looking over there, moving around just to get it to crash.

**Comment by OreCruncher** [comment]
Can I get your forge logs?

EDIT:
- Is the spawn point near the furnace, like same chunk or adjacent chunk?
- Did anything strange happen during the placement of the furnace?

What this is telling me is that the special renderer is being triggered for the Furnace, and the TE attempts to get the blockstate from the world object which is air.  Something is lying. :)

**Comment by SonicX8000** [comment]
In the test World... spawn is near the furnaces in the same chunk by the looks of it. Although in my survival world it's the adjacent chunk.

Nothing strange happened while placing the furnaces.

Forge Log...? I dunno if this is it. This is from a test world with the furnaces & spawn in the same chunk.
https://pastebin.com/JZ5ax9St

**Comment by OreCruncher** [comment]
Hmm....would it be possible for you to try with Forge 2772?  Reason I ask is that is what I am using in my dev environment and I cannot repro the issue.  It seems it should be real easy to do that but for some reason I can't get it to break.

**Comment by SonicX8000** [comment]
Sure. Here's the crash report & forge log using Forge: 14.23.5.2772

Crash:
https://pastebin.com/RiVMsvW4

Log:
https://pastebin.com/3gtingHj

This one took about 6 respawns for it to crash, it's random. If you want, I could send you the world I'm using, do you have a discord or something?

**Comment by OreCruncher** [comment]
Managed to trigger it with a modpack I am working on.  Smells timing related.  Off to test a fix.

**Comment by OreCruncher** [comment]
Pushed v0.2.3.2 to CurseForge.
