### ISSUE TITLE
Shops not being synced on LAN server

### ISSUE THREAD

**Issue by ejektaflex** [OreCruncher/Doodads#7]
Currently, I'd love to add this mod just for the shops but at least in a LAN world the state of shops does not seem to be completely synced. Items with the green background do not show up in the shop menu for another person until they log out and log in. Also, they do not visually show up on the shelf until the player logs out and logs back in. It might work on a server, but I'd rather not try it out live until it works in a world that's open to LAN.

Using Patchwork-1.12.2-0.2.3.2BETA & Forge 2796.

**Comment by OreCruncher** [comment]
The ones in green don't show?  What about red?  Also, do you notice the inventory contents changing?  For example, if it's your shop shelf and you have it open to the config screen, if a player makes a trade do the items show up in the inventory?

EDIT:  These may seem like weird questions but it will help me identify where in the code to start looking.

**Comment by MokahTGS** [comment]
We are having this issue on a dedicated server as well.  Our server is hosted locally with local ips.  One dedicated server and three machines all joining in a local connection.

For us, the owner's inventory contents are not changing, nor does the inventory receive coins. A non-owner can see the amount of coins to pay, but not the item she is purchasing. I can click on the item slot and receive the item and it subtracts coins from my inventory, but the owner is not receiving the coins or losing any inventory.

**Comment by OreCruncher** [comment]
OK.  Think I fixed the syncing issues.   I need to do more testing before I push a new build.  Just thought I would let you guys know.

**Comment by OreCruncher** [comment]
Pushed v0.2.3.3 to CurseForge with the fixes.  Note the dependency on a newer OreLib as well as Forge 2779+.
