### ISSUE TITLE
methodical right of flight repeatedly disconnects player

### ISSUE THREAD

**Issue by Yoghurt4C** [OreCruncher/Doodads#8]
https://pastebin.com/6ruTpTzN

patchwork 1.12.2-0.2.3.2BETA
forge 2796

**Comment by OreCruncher** [comment]
Can you link the complete log?   Need some more info on your environment.

**Comment by Yoghurt4C** [comment]
[latest.log](https://github.com/OreCruncher/Patchwork/files/2710895/latest.log) :joy_cat:

**Comment by OreCruncher** [comment]
Pushed v0.2.3.3 to CurseForge with the fixes. Note the dependency on a newer OreLib as well as Forge 2779+.
